### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by jackniklason** [KwatMDPhD/FeatureSetEnrichment.jl#1]
<img width="582" alt="Screen Shot 2021-01-06 at 2 08 45 PM" src="https://user-images.githubusercontent.com/50241841/103820020-c6d9ab80-5028-11eb-98c1-7a6b18090b9f.png">

**Comment by KwatME** [comment]
I think this error is saying that SEA's requirement, Information, has no version set. But, this un-versioned Information is still installed. So, SEA should work even thought you see this error.

I tried to install and ran SEA. it worked.

After the installation, test it by
```sh
$ julia --eval 'using SEA; score_set(["a", "b", "c"], [1.,2.,3.], ["a", "b"])'  
```

**Comment by KwatME** [comment]
You can install SEA.jl only and test. Let me know if it works. I'm fixing the sea (python) one now.

**Comment by KwatME** [comment]
If this does not work, reopen this issue. Closing it for now.

**Comment by jackniklason** [comment]
<img width="917" alt="Screen Shot 2021-01-06 at 3 31 54 PM" src="https://user-images.githubusercontent.com/50241841/103826633-6a7c8900-5034-11eb-867c-8d505a771a81.png">

still having trouble with this one

**Comment by KwatME** [comment]
add(url="")

**Comment by KwatME** [comment]
We add SEA.jl directly from github. When it becomes stable, I will release it. When adding a package from GitHub, use add(url="...")

**Comment by jackniklason** [comment]
I think I did that first. but when I type 'using SEA;' it gives me, 
ERROR: ArgumentError: Package SEA not found in current path:
- Run `import Pkg; Pkg.add("SEA")` to install the SEA package.

then this is where I'm testing if the package is installed


<img width="917" alt="Screen Shot 2021-01-06 at 3 31 54 PM" src="https://user-images.githubusercontent.com/50241841/103827377-12df1d00-5036-11eb-857c-9f64953bf50b.png">

**Comment by KwatME** [comment]
U were right. Let me fix that.

**Comment by KwatME** [comment]
Can u try again?

**Comment by KwatME** [comment]
Wait like a minute and try again please.

**Comment by jackniklason** [comment]
<img width="837" alt="Screen Shot 2021-01-06 at 4 10 09 PM" src="https://user-images.githubusercontent.com/50241841/103831631-b41ba280-5039-11eb-81c7-675333fbf644.png">


same error

**Comment by KwatME** [comment]
Ok - it looks like I need to register all of my packages for my packages to depend on each other. Let me change the installation script. Give me 10min.
